version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./html:/var/www/html
    ports:
      - "80:80"
      - "443:443"
  
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./html:/var/www/html
  
  mariadb:
    image: mariadb:latest
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      
volumes:
  db_data: {}
