version: '2'
services:
  db:
    image: mariadb:10.3.16
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
  web:
      build: ./web
      ports:
        - '80:80'
        - '443:443'
      volumes:
        - ./html/:/var/www/html/:cached
        - ~/.ssh:/root/.ssh
        - ./cert:/etc/pki/ssl
      depends_on:
        - db
        - mailhog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"