version: "3.9"
services:
  apache:
    build: apache2
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    #   - php-fpm
    volumes:
      - ./html/:/var/www/html/:cached
      - ~/.ssh:/root/.ssh
      - ./cert:/etc/ssl/local/certs
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./html:/var/www/html:cached
    depends_on:
      - db
      - mailhog
  db:
    image: mariadb:10.3.16
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
