version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    ports:
      - "{port(example/13306)}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '{password}'
  web:
      build: ./web
      ports:
        - '{yoursetting(example/80)}:80'                    
      volumes:
        - ./html:/var/www/html         
      depends_on:
        - db